### PR TITLE
Render the main element consistently in IE

### LINKED ISSUE #727: `main` has been removed but is needed for IE 11
```css
main {
    display: block;
}
```
is needed for IE 11 to render the element properly. Probably also for IE 10.

### PR DESCRIPTION
**Pull request by thasmo**
Fixes #727 by rendering the main element as block-element for IE.

### CODE REVIEW

**Comment by jonathantneal** [comment]
@thasmo, nice, but would you specify the target browser(s)?

**Comment by thasmo** [comment]
Sure, where exactly? In the PR title, commit message, comment? :)

**Comment by jonathantneal** [comment]
Line 28, where you specified **all browsers*. https://github.com/necolas/normalize.css/pull/730/commits/55f0ce1a29a6669de43ec80096f7ce88bb067688#diff-bb3dde41d97f19be8ab7b4780a915d5eR28

Before it was removed, I had specified `Add the correct display in IE` here:

https://github.com/necolas/normalize.css/blob/6.0.0/normalize.css#L49

**Comment by thasmo** [comment]
@jonathantneal, done. 👍

**Comment by thasmo** [comment]
Oh, I see. On it.

**Comment by jonathantneal** [comment]
Just putting `IE` will do, because that means all versions. I hope other IE11 styles weren’t lost, unless this project no longer supports IE11 either.

**Comment by jonathantneal** [comment]
I know it sounds really picky, but `IE 9-11` would not be accurate, because IE8 did not support `main` 🤷‍♂️  and this project doesn’t support IE9 or IE10 AFAIK.

**Comment by thasmo** [comment]
@jonathantneal, last chance. :P

**Comment by thasmo** [comment]
Actually, last chance now. ;)

**Comment by thasmo** [comment]
Typed enough Is and Es today. 👍

**Comment by thasmo** [comment]
I believe IE 10 is supported, at least that's what's documented but I'd be happy to only have support for IE 11.

**Comment by jonathantneal** [comment]
Yea, it’s not complicated. The comment just needs to blanket IE.

It will also need to use the same voice as the other comments, which would be:

```
Add the correct display in IE
```

That’s not the message you’ve written, as you’ve introduced new terms like `Render` and `consistently`. As picky as it sounds, you’d likely lose that one line in git blame 😄 but otherwise this looks great and I hope it’s merged.

I really have zero control over this. I’m just looking out for the project as best I can.

**Review by nzec — APPROVED** [review]
Looks good! 👍

**Comment by fritzmg** [comment]
👍 this caused some headache for me in a current project where the `<main>` element was used and the `padding` for example had no effect in IE. I didn't realize IE 10+ does not treat `<main>` as a block level element automatically.

**Comment by thasmo** [comment]
🤔

**Comment by Tetonne** [comment]
get standard scrollbar (safari)

**Comment by garrettw** [comment]
@thasmo @Tetonne please do not post meaningless/spam comments.

**Comment by fritzmg** [comment]
Geez, _exactly_ 3 months later I stumbled over the same issue - at least it only cost me half an hour this time, until I figured it out... __again__ 😁 

Why has this not been merged and released in 8.x?

**Review by GarethPW — APPROVED** [review]

**Comment by fritzmg** [comment]
@necolas the NPM package still only has 8.0.0: https://www.npmjs.com/package/normalize.css?activeTab=versions
Could you may be check why?

**Comment by necolas** [comment]
Forgot to publish. Should be up now. Thanks

**Comment by nzec** [comment]
@necolas Thanks! ❤️

**Pull request closed without merging**
