### PR TITLE
Correct the width and height on 'body' element in all browsers

### PR DESCRIPTION
**Pull request by nazarepiedady**

### CODE REVIEW

**Comment by mvasilkov** [comment]
I would assume this is out of scope for normalize.css (also why set width at all).

**Comment by garrettw** [comment]
Which browsers need this to match the rest?

**Comment by mvasilkov** [comment]
@garrettw it's not the default in any browser I know of.

**Comment by nazarepiedady** [comment]
sorry guys, i think that could be a good features for normalize.css, because i had some problems with this, i want to add this properties to optimize the job.

**Comment by garrettw** [comment]
@nazarepiedady The point of normalize.css is only to fix browser behavior that is outside the norm established by other browsers. They have moved away from these so-called "opinionated" styles because, while they might be nice to have, they are not in line with this project's goals.

**Comment by nazarepiedady** [comment]
sorry, I really sorry!.

**Comment by necolas** [comment]
No thanks. This changes the default `body` layout. That's something you can do in your own code if you want.

**Pull request closed without merging**
