### PR TITLE
Fix typo in normalize.css

### PR DESCRIPTION
**Pull request by netergart**
Remove duplicate font family
```css
font-family: monospace, monospace;
```

### CODE REVIEW

**Comment by miquelfire** [comment]
#695

Still needed.

**Comment by fisker** [comment]
what makes you think its typo https://github.com/necolas/normalize.css/blob/master/README.md#extended-details-and-known-issues

**Comment by Michaelsy** [comment]
> #695 
> Still needed.

@miquelfire 
What do you mean with "still needed"? This PR or the double "monospace"?

**Comment by miquelfire** [comment]
The double monospace

**Pull request closed without merging**
