### PR TITLE
Remove all opinionated rules

### PR DESCRIPTION
**Pull request by jonathantneal**
- Remove changing the default font family in all browsers.
- Remove the removal of margin on body in all browsers.
- Remove the removal of outline on focused links when they are also
active or hovered in all browsers (opinionated).
- Remove changing the font styles of input controls in all browsers.
- Remove the changing of border, margin, and padding of fieldsets in
all browsers.

### CODE REVIEW

**Comment by zemirco** [comment]
Happy new year :smile: 

What's the status of this issue?

**Comment by englishextra** [comment]
> Remove changing the default font family in all browsers.
    Remove the removal of margin on body in all browsers.
    Remove the removal of outline on focused links when they are also
    active or hovered in all browsers (opinionated).
    Remove changing the font styles of input controls in all browsers.
    Remove the changing of border, margin, and padding of fieldsets in
    all browsers.

I already add first thing after font-face paths and normalize, a normalizer of normalizer, i.e I remove webkit outline on focused links and select/buttons. By the way,
thanks for `Remove changing the font styles of input controls`, and `Remove the changing of border, margin, and padding of fieldsets`

**Comment by jonathantneal** [comment]
@zemirco, it is merged, tagged, and published.

normalize.css no longer includes opinionated rules, and focuses exclusively on browser normalization.

**Comment by KingScooty** [comment]
Thanks for removing this stuff. I'm confused/slightly annoyed how opinionated rules made their way into this project in the first place!

**Comment by ur5us** [comment]
@jonathantneal Can you elaborate a little what constitutes an opinionated rule? For instance, I'd assume that the font settings for input elements are not the same across different browsers so it'd make sense to normalize things like `font-size` et al.

**Comment by englishextra** [comment]
@jonathantneal In my case select's font-family set to sans-serif broke lots of styles. Form elements styling is an ungracious task.

**Pull request merged**
