### PR TITLE
Auto hide persistent scrollbar in Edge, IE 10/11

### PR DESCRIPTION
**Pull request by jonathantneal**
Prevents content shift due to the scrollbar in Edge and IE 10/11.
Aligns Windows IE 10/11 and Edge experience with Mac.

### CODE REVIEW

**Comment by brunowego** [comment]
+1

**Comment by thierryk** [comment]
I understand that this fits into the "normalize" philosophy but I think it is worth considering [these tweets](https://twitter.com/aardrian/status/645356175446421504) from Adrian Roselli: 

> “Should You Use a Custom Scroll Indicator? A Study with Eye-Tracking”
> https://viget.com/inspire/should-you-use-a-custom-scroll-indicator-a-study-with-eye-tracking …
> No. At best, waste of dev. At worst confusing.

and 

> I also think custom styling is bad and removing like OSX & mobile do is poor UX. So I think this is a terrible idea

**Comment by jonathantneal** [comment]
@thierryk, a custom scroll indicator (which I’ve seen a lot of news websites doing lately) is very different than this.

That study proved that users just scrolled to get a feel for where where they were at, and this change would have no impact on that behavior.

As you mentioned, this fits into the “normalize” philosophy. It normalizes behavior across devices and improves a the less-than-ideal experience in IE where scrollbars shift content.

**Comment by thierryk** [comment]
@jonathantneal I only mentioned the first tweet because Adrian replied in that context saying "I also think [auto hiding persistent scrollbar] is a terrible idea."

Another [tweet](https://twitter.com/capndesign/status/640192899909578752) from that thread: 

> It seems like this would confuse regular Edge/IE users. What's the benefit?

**Comment by cvrebert** [comment]
I'd advise against this change. In IE11 (and potentially IE10) the auto-hiding scrollbar shows itself too easily, making it difficult to click things on the right edge of the viewport since they get overlapped by the scrollbar. See https://github.com/twbs/bootstrap/issues/18543

**Comment by jonathantneal** [comment]
@thierryk, @cvrebert, you are right. This contradicts the expected Windows behavior. Thanks much for chiming in. I’m closing this.

I also looked at twbs/bootstrap#18775 as a possible change, but changing the latest Edge expectation seems equally opinionated, so perhaps this is best left in Bootstrap. @cvrebert, since you’ve been following both issues, any concerns or objections?

**Comment by cvrebert** [comment]
@jonathantneal Yes, I think tinkering with this is too opinionated for Normalize. IMO, scrollbar behavior ought to match the norm for the respective platform that the browser is running on, and querying for that norm isn't currently possible from CSS.
We only reluctantly set it in Bootstrap because being responsive via `@-ms-viewport` is more important to us, but causes https://github.com/twbs/bootstrap/issues/18543 as a side-effect, and setting `-ms-overflow-style` was the least-worst workaround we could find.

**Pull request closed without merging**
