### PR TITLE
Make normalize.css available for webpack

### PR DESCRIPTION
**Pull request by yoihito**

### CODE REVIEW

**Comment by anEffingChamp** [comment]
I support it. If this is all it takes then I see no reason not to.

**Comment by Semigradsky** [comment]
@yoihito You can use normalize with webpack, but with weird syntax: `require('normalize.css/normalize.css');`

It would be nice if PR will accept.

**Comment by maxdow** [comment]
+1

**Comment by srn** [comment]
Seems like a duplicate for https://github.com/necolas/normalize.css/pull/384

**Comment by necolas** [comment]
merged from 384

**Pull request closed without merging**
