### PR TITLE
Changed ButtonColor to inherit.

### PR DESCRIPTION
**Pull request by colshacol**
Not quite sure if this line was meant just to cancel out any color added, or if it used to be a variable in some preprocessor.

### CODE REVIEW

**Comment by mattbrundage** [comment]
ButtonText is a [system color](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#System_Colors) and its use here in intentional.

**Comment by adamralph** [comment]
https://jigsaw.w3.org/css-validator/ tells me

> The value 'ButtonText' is deprecated

**Comment by jonathantneal** [comment]
What @mattbrundage said :)

**Comment by adamralph** [comment]
From the link posted by @mattbrundage:

>  Not all system colors are supported on all systems. 👎 for use on public web pages.

**Pull request closed without merging**
