### PR TITLE
Fix <sup> property

### PR DESCRIPTION
**Pull request by lnfnunes**
<sup> text isn't aligned with normal text cropping the top a little bit.
Check it out: http://codepen.io/lnfnunes/pen/vOrKeV

### CODE REVIEW

**Comment by robsonsobral** [comment]
Which browser?

**Comment by Tigt** [comment]
Screenshot of the text being cut off as described

Happening to me in Firefox for OS X.

**Comment by lnfnunes** [comment]
- Chrome 43 for (Linux / Windows)
Chrome

- Firefox 39 (Windows)
Firefox

- Internet Explorer 11 (Windows)
IE

**Comment by battaglr** [comment]
Also happening on Chrome 43 for OS X.

@lnfnunes: `.25` seems a little low; maybe we can try with a `.3`, `.35` or `.4` —we also need to consider the font in use.

**Comment by lnfnunes** [comment]
Looks like the major render problem is in Chrome and  I´ve realized setting the _line-height_ to &lt;sup&gt; parent element fixed this issue even with font-family variations.
```css
p { line-height:1.2 }
```
I´ve updated the test case: http://codepen.io/lnfnunes/pen/vOrKeV

I don´t think be possible to normalize.css fix this... __unless__ adding the line-height to all "text" elements.
Does it make sense?

**Pull request closed without merging**
