### PR TITLE
Added minify support

### PR DESCRIPTION
**Pull request by ardagedikk**
I think it would be better to present the reduced size.
Size before shrinking 7.27kb, size after shrinking 2.28kb

### CODE REVIEW

**Comment by jonathantneal** [comment]
Hi @ardagedikk, I appreciate your consideration for the bytes. It may have saved you some time to check the issue tracker. It was resolved to let the end-user minify the library.

> Going with this: people can minify using that online YUI Compressor-based tool (included in the readme), or as part of their build process.
> — https://github.com/necolas/normalize.css/issues/4#issuecomment-1783421 (Aug 11, 2011)

Don’t feel too bad. In the last six years, it comes up again from time to time. See #4, #75, #81, #116, #131, #146, #224, #338, #352, #382, #410, #632.

Finally, some good news — you can still get what you want. The recommended CDN already provides a minified version for this library. See https://cdnjs.com/libraries/normalize

**Comment by ardagedikk** [comment]
It could be a good solution for those who don't want to use CDN and don't want to deal with minifying

**Comment by garrettw** [comment]
Why wouldn't you want to use CDNjs? It's hosted -- you don't have to pay for your own CDN. It's literally just as easy as linking to your own CSS file on your website. I can't think of a good reason not to use it.

**Comment by ardagedikk** [comment]
I am not against using CDN, but I think the use of CDN in projects where there is a lot of dependency is a disadvantage in managing dependencies. In such cases it is logical to install the package with the package manager and use the minify state.

**Comment by jonathantneal** [comment]
I still believe this should be closed. Again, this has been addressed in the issue tracker.

**Comment by necolas** [comment]
Yeah this has been discussed before. Thanks but I won't be merging

**Pull request closed without merging**
