### PR TITLE
Create normalize.min.css

### PR DESCRIPTION
**Pull request by joedanhol**
Faster loading times

### CODE REVIEW

**Comment by TrySound** [comment]
I think you need to add builder with minificator. I use gulp, it's pretty and simple.

**Comment by necolas** [comment]
I suggest that you use a build tool to optimize your assets. There are several good Node.js tools for doing that with CSS.

**Comment by samayo** [comment]
Why not include a minified version here? like foundation, bootstrap, semantic-ui ... Not everyone uses gulp or front-end package management when developing.

**Comment by TrySound** [comment]
Uglify CLI?

**Comment by samayo** [comment]
Nope. I am just a PHP dev. I threw in normalize to create a simple page. Anyway, I googled and found a minifying site..

**Pull request closed without merging**
