### PR TITLE
Fixed repository line in package.json

### PR DESCRIPTION
**Pull request by garrettw**
It probably doesn't relate to #719, but I did notice this one thing that looked off, so I thought I'd fix it just in case.

### CODE REVIEW

**Comment by jonathantneal** [comment]
Hello. This doesn’t fix anything. See https://docs.npmjs.com/files/package.json#repository

> For GitHub, GitHub gist, Bitbucket, or GitLab repositories you can use the same shortcut syntax you use for npm install.

**Comment by garrettw** [comment]
😞

**Comment by jonathantneal** [comment]
Thanks for offering a contribution. No need to be sad. You are just trying to help. 😄

**Comment by garrettw** [comment]
I know, I just feel a bit stupid, that's all 😝

**Pull request closed without merging**
