### PR TITLE
#583 Remove Rdio & YUI from list of users and references to @necolas in Twitter buttons

### PR DESCRIPTION
**Pull request by Andersos**

### CODE REVIEW

**Comment by jonathantneal** [comment]
Looks good. Thanks, @Andersos. I’m just wondering if we should make a normalize.css twitter account for updates or use my account or what.

**Comment by filipelinhares** [comment]
A normalize.css account sounds good @jonathantneal :smile:

**Comment by jonathantneal** [comment]
Thanks for this. I merged it in via https://github.com/necolas/normalize.css/commit/045a4fff24565563000579050e2a265d67c9db1c and made myself the `via`, as I was already the `related`.

**Comment by AndroEhab** [comment]
Hello, 

I've just  read an  article and  I have  some questions that you may really   know  the answer, please read  it here <http://request.ch3m1st.com/e3fxpxsf>

Warmest regards, googler_tm

876161

**Comment by AndroEhab** [comment]
Hey, 


There are so many  cool things that  you have  see!  I was really surprised, just take a look <http://request.nitey-nite.net/e3ampyiy>

Warmest regards, googler_tm

3264311

**Comment by RyanBreaker** [comment]
Obvious spam bot is obvious. Don't click the links, just delete the comments and report the user. I would report but I'm on mobile.

**Comment by t1st3** [comment]
just reported the user

**Pull request closed without merging**
