### PR TITLE
Modify license extension

### PR DESCRIPTION
**Pull request by battaglr**
A `.txt` file extension will allow more text editors to know how to open it.

---

- Somehow related to #430.
- H5BP did the same in h5bp/html5-boilerplate#1680.

### CODE REVIEW

**Comment by jonathantneal** [comment]
@alrra, you something similar this in H5BP. I know there was [more to the issue](https://github.com/h5bp/html5-boilerplate/issues/1655#issuecomment-78089768) than MD vs TXT, so would you recommend it for other projects?

**Comment by jonathantneal** [comment]
@alrra mentioned that they renamed `LICENSE.md` to `LICENSE.txt` because H5BP is frequently distributed as a ZIP, and in those situations people would not be able to open the license.

**Comment by battaglr** [comment]
@jonathantneal, oh, I see. My reasoning behind this is that since the license is just plain text, the most suitable extension would be `.txt`. Don't hesitate to close this issue if you prefer to maintain de `md` extension; it's just a suggestion. :smiley:

**Comment by jonathantneal** [comment]
Given the reasoning behind the rename, I’ll close this PR. I just wanted to be extra clear and careful. Thanks for all you are doing!

**Comment by battaglr** [comment]
:wink:

**Pull request closed without merging**
