### PR TITLE
Remove opinionated cursor styles on buttons

### LINKED ISSUE #544: No pointer cursor on file and image inputs
Should have a pointer cursor hover file and image inputs in all browsers:
[type='file'],
[type='image'] {
	cursor: pointer;
}
[type='file']::-webkit-file-upload-button {
	-webkit-appearance: button;
	cursor: pointer;
}

### PR DESCRIPTION
**Pull request by jonathantneal**
Resolves #544 and #371

### CODE REVIEW

**Comment by thierryk** [comment]
LGTM

**Comment by TrySound** [comment]
Hey, it can break a lot of styles. I always expect clickable button like link.

**Comment by battaglr** [comment]
LGTM!

**Comment by jonathantneal** [comment]
@TrySound, please see https://github.com/necolas/normalize.css/issues/371#issuecomment-60072171

**Pull request merged**
