### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by cvrebert**
Per https://github.com/bower/bower.json-spec/commit/a325da3d79baab018c572d75dc1781b12322f6cd

### CODE REVIEW

**Comment by necolas** [comment]
i think i'll just drop explicit bower support next release

**Comment by cvrebert** [comment]
:clap: :clap: Sounds good :+1:

**Comment by cvrebert** [comment]
I salute your bravery sir. 🎖 Stay strong against the inevitable backlash. :heart:

**Comment by alexwilczewski** [comment]
Take this post as curiousity, not as "the inevitable backlash". What is the reason to remove bower support? Is it because with bower you can explicitly reference the git repo?

**Comment by FagnerMartinsBrack** [comment]
There is no need for `bower.json` since you can download the whole repository and run the build programatically. Also, the community seems to be slowly dropping bower in favor of npm.

The inevitable backslash seems to be from the ones that rely in some features from `bower.json` like the files that are ignored through the `ignore` array, the `license` config (where some tools use to audit the dependency licenses), the `main` property that maps the main file, etc.

**Comment by olach** [comment]
Sad to see Bower support go away. I don't agree that this is the way to go. But I understand that having to support multiple package managers takes some time.

I know I'm still able to fetch packages with Bower directly from the Github repo. So I can still use Bower. But I really don't understand those who prefer to use npm instead of Bower.

IMHO npm is only for Node packages. I use it mostly for all build scripts. It just feels wrong to keep front end assets like css-files in the node_modules folder, together with mostly development/server code and build scripts.

In some projects, its also useful to commit Bower components into the repo.

I guess the chances to re-add Bower support is minimal, so I don't open a new issue on this topic, but I write here in this thread to express my opinion on this topic. Not all of us developers likes the current trend of moving away from Bower to npm.

**Comment by dcdeiv** [comment]
@olach :+1: :+1: :+1: 
I use npm for tests and task runners, and bower for clean, pluggable, front-end packages like normalize.css. Also it has not to be maintained like npm (you don't have to `npm publish` every time). So you could have kept it and made everybody happy :broken_heart:

**Pull request closed without merging**
