### PR TITLE
List removal of `main` field from `package.json`

### PR DESCRIPTION
**Pull request by battaglr**
- List removal of `main` field from `package.json` in the CHANGELOG file.
- Mark files with code syntax to be consistent with the CONTRIBUTING file.

### CODE REVIEW

**Comment by SimenB** [comment]
Why was `main` removed? And if it'll remain that way, how about adding a `style` field instead, like parceliify expects?

https://github.com/rotundasoftware/parcelify

**Comment by battaglr** [comment]
@SimenB, hi! That's something I don't know much about (parceliify). Further discussion about this is taking place on #542; in here your opinion *may* get lost in the issue tracker. :wink:

**Comment by jonathantneal** [comment]
I’d like to restore `main` to resolve #542

**Comment by battaglr** [comment]
Closing because of #564.

**Pull request closed without merging**
