### PR TITLE
Update normalize.css

### PR DESCRIPTION
**Pull request by ttzc**

### CODE REVIEW

**Comment by garrettw** [comment]
This does not fix anything useful or important.

**Comment by clarfonthey** [comment]
Great commit name. 10/10

**Comment by tniezurawski** [comment]
I have a feeling that `normalize.css` is under some attack. The majority of PRs look like raised by bots 🤔 I can't figure out why.

**Comment by ttzc** [comment]
I isn't robot.

**Comment by bronzehedwick** [comment]
Then can you explain the value of this change, @ttzc?

**Comment by ttzc** [comment]
No, I can't

**Comment by bronzehedwick** [comment]
Okay, then can you close this PR @ttzc? Thanks.

**Comment by foltra** [comment]
lol, this is just changing a line break to a comment line? i guess it's a poor attempt at filling github dashboard with commits.

**Pull request closed without merging**
