### PR TITLE
Add sass file

### PR DESCRIPTION
**Pull request by ppsirius**
On github we can find many repo with normalize in sass, why don't make this file on official repository?
+ file ready to import
+ output css a half smaller than file with comments

### CODE REVIEW

**Comment by battaglr** [comment]
@ppsirius, hi! Thank you for taking the time to do this! Preprocessors or transpilers such as Sass have been the topic of many issues, such as #450, #446, #290, and [the list goes on and on](https://github.com/necolas/normalize.css/issues?utf8=%E2%9C%93&q=sass).

Before releasing v4 we considered this, since it has been asked many times, but we really couldn't find what value could it bring.

In all preprocessors/transpilers that I know of, you can import a vanilla CSS; and while I agree "silent" comments are great, that doesn't justify maintaining two different files. If we decided to merge this, what about Less or Stylus, or any flavour of PostCSS, which would be our argument to not accept them —and end up maintaining lots of different files with mostly different extensiones?

**Comment by ppsirius** [comment]
I agree with you, You should add other preprocessors. This files give us possibility to clean fast comments in output. Reducing the file size from 7kb to 3kb i think is enough reason. Otherwise on github you will see a bunch of duplicated repo.

**Comment by TrySound** [comment]
@ppsirius If you care about style size use css minifiers. If you use preprocessors I think it's not so big deal to add something in pipe.

**Comment by TrySound** [comment]
@ppsirius Your way is opposite to DRY.

**Comment by greypants** [comment]
I think for a while trying to `@import` css files would default to the native css `@import` and link to an external file rather than pull in the file directly like it does with scss/sass.  

This was [fixed in `node-sass`](https://github.com/sass/libsass/pull/754) and now works fine if you leave off the `.css` extension.

I added this to my sass options:

```js
includePaths: [
  "./node_modules/normalize.css"
]
```

And can `@import` the `normalize.css` file just fine in my main `.sass` file.

```sass
@import normalize
```

**HOWEVER**, @battaglr, [this is still an issue in Ruby Sass](https://github.com/sass/sass/issues/556), and duplicating `normalize.css` as `normalize.scss` in this repo, would fix the problem for a lot of people. This project (normalize) was the use case mentioned in the issue.

It's a super easy add (`cp normalize.css normalize.scss`), and like @ppsirius said, would remove the need for forks like https://github.com/JohnAlbin/normalize-scss

**Comment by battaglr** [comment]
@ppsirius, please, keep in mind that *development code* is not the place for optimizations such as this one —if you're concerned with size, as @TrySound suggested, in your *production code* you may consider using a minifier. Please, [don't forget that the detailed comments are an important aspect of this project](https://github.com/necolas/normalize.css#what-does-it-do).

@greypants, hi! Thanks for correcting me on this; I didn't know Ruby Sass had this behaviour. I'm not in charge of making any decisions, but regardless of how easy or difficult including this here could be, usually the best/right thing to do is to put the energy on solving the *problems or limitations* of a given project in said project, and not trying *patch* other projects because said *problems or limitations*. FWIW @chriseppstein himself wrote a `gem` to allow *fix* that: [sass-css-importer](https://github.com/chriseppstein/sass-css-importer).

**Comment by jonathantneal** [comment]
It’s a noble idea, but if or when we introduce a Sass, Scss, Stylus, or Less version, or any other version, it will be generated from a true CSS source. Perhaps PostCSS can do this. May all of these extensions be generated in PostCSS?

For now, we must not repeat ourselves. I allowed for this in [sanitize.css](https://github.com/10up/sanitize.css/tree/master/lib) and now upgrades are a beast. So, I have experience going the other way, and I can say with confidence that it has hurt the project.

**Pull request closed without merging**
